### ISSUE TITLE
Move this repo to a new org?

### ISSUE THREAD

**Issue by ryanj** [hpgrahsl/rhsummit23-backstage-gpts#22]
We should figure out a longer-term home for this content

We can potentially move these templates upsteam to: https://github.com/janus-idp/software-templates

We should discuss the tradeoffs around moving this content upstream before we make any changes

**Comment by ryanj** [comment]
It would be good to rename some things if we're going to upstream it - possibly rename to: map-frontend, map-gateway, and map-backend?  I'm not sure if "poi" is an acronym that is recognizable enough.

**Comment by ryanj** [comment]
I like the idea of moving this content under https://github.com/redhat-scholars/backstage-workshop as well

**Comment by hpgrahsl** [comment]
@ryanj yes. as discussed I'll do one final dry-run myself tomorrow and then move it into the above mentioned repo. also, I'll take the opportunity to remove the meanwhile heavily outdated content in its `app` folder.
