### ISSUE TITLE
Automatically load backend dataset on boot

### ISSUE THREAD

**Issue by ryanj** [hpgrahsl/rhsummit23-backstage-gpts#23]
Should we simplify the workflow by automatically loading the parks dataset when the backend service is initialized?

**Comment by hpgrahsl** [comment]
I'll provide a config param for that which will default to true to auto-load the data. In case we decide to not want this behaviour we can fallback easily.

**Comment by hpgrahsl** [comment]
will be addressed by #26

**Comment by hpgrahsl** [comment]
done
